version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Installing dependencies"
      - npm install
      - npm install -g @angular/cli@13.0.3
    build:
      commands:
        - echo "Building Angular project"
        - ng build --prod
    post_build:
      commands:
        - echo "Updating files in S3 bucket"
        - aws s3 sync dist/nssa/ s3://nssa --delete
